--- 
jobs: 
  build: 
    docker: 
      - 
        image: "circleci/node:12-browsers"
    steps: 
      - 
        checkout: 
          path: ~/myapp
      - 
        restore_cache: 
          key: "agenda-angular-{{ .Branch }}-{{ checksum \"package-lock.json\" }}"
      - 
        run: "npm install"
      - 
        run: "webdriver-manager update --standalone false --gecko false"
      - 
        save_cache: 
          key: "agenda-angular-{{ .Branch }}-{{ checksum \"package-lock.json\" }}"
          paths: 
            - node_modules
      - 
        run: "npm run test -- --progress=false --watch=false --browsers=ChromeHeadless"
      -
        run: "npm run e2e -- --protractor-config=e2e/protractor.conf.js"
    working_directory: ~/myapp/agenda-angular
version: 2
