--- 
jobs: 
  build: 
    docker: 
      - 
        image: "circleci/node:12-browsers"
    steps: 
      - 
        checkout: 
          path: ~/myapp
      - 
        restore_cache: 
          key: "agenda-angular-{{ .Branch }}-{{ checksum \"package-lock.json\" }}"
      - 
        run: "npm install"
      - 
        save_cache: 
          key: "agenda-angular-{{ .Branch }}-{{ checksum \"package-lock.json\" }}"
          paths: 
            - node_modules
      - 
        run: "npm run test -- --progress=false --watch=false --browsers=ChromeHeadless"
    working_directory: ~/myapp/agenda-angular
version: 2